import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Context from './Context'
import Header from '@/components/header/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={inter.className}>
        <Context>
          <Header />
          {children}
        </Context>
      </body>
    </html >
  )
}
